# Generated by Django 3.1.7 on 2021-06-22 08:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0002_auto_20210612_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 8, 37, 13, 726666, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 22, 8, 37, 13, 725687, tzinfo=utc)),
        ),
    ]
