# Generated by Django 3.1.7 on 2021-06-24 07:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20210622_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 7, 23, 7, 524633, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 7, 23, 7, 523620, tzinfo=utc)),
        ),
    ]
