# Generated by Django 3.1.7 on 2021-06-24 09:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import samples.models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0007_auto_20210624_0823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 9, 22, 28, 528704, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 9, 22, 28, 527294, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='file',
            field=models.FileField(upload_to=samples.models.user_directory_path_project, validators=[samples.models.validate_project_extension]),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 24, 9, 22, 28, 527787, tzinfo=utc)),
        ),
    ]
