# Generated by Django 3.1.7 on 2021-06-28 16:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0009_auto_20210628_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 21, 47, 302622, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='project',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 21, 47, 300933, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='sample',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 28, 16, 21, 47, 301432, tzinfo=utc)),
        ),
    ]
